import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url))

const sourceFiles = {
  favicon: "assets/brand/favicon.ico",
  webuiWordmark: "assets/brand/webui-wordmark.webp",
  wordmark: "assets/brand/wordmark.webp",
} as const

type SourceName = keyof typeof sourceFiles

interface BinaryOutput {
  destination: string
  source: SourceName
}

const binaryOutputs: readonly BinaryOutput[] = [
  {
    destination: "apps/docs/public/favicon.ico",
    source: "favicon",
  },
  {
    destination: "apps/webui/public/favicon.ico",
    source: "favicon",
  },
]

const runtimeFaviconDestination = "apps/runtime/src/assets/favicon.ts"
const isCheck = process.argv.slice(2).includes("--check")
const unknownArguments = process.argv.slice(2).filter((argument) => argument !== "--check")
const staleOutputs: string[] = []

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error)
  console.error(`Brand asset synchronization failed: ${message}`)
  process.exitCode = 1
})

async function main(): Promise<void> {
  if (unknownArguments.length > 0) {
    throw new Error(`Unknown arguments: ${unknownArguments.join(", ")}`)
  }

  const sourceBuffers = new Map<SourceName, Buffer>()

  for (const [name, relativePath] of Object.entries(sourceFiles) as [SourceName, string][]) {
    sourceBuffers.set(name, await readFile(resolveRepositoryPath(relativePath)))
  }

  for (const output of binaryOutputs) {
    const source = sourceBuffers.get(output.source)
    if (!source) {
      throw new Error(`Brand asset source was not loaded: ${output.source}`)
    }
    await synchronizeOutput(output.destination, source)
  }

  const favicon = sourceBuffers.get("favicon")
  if (!favicon) {
    throw new Error("Brand favicon source was not loaded")
  }

  await synchronizeOutput(
    runtimeFaviconDestination,
    Buffer.from(createRuntimeFaviconModule(favicon), "utf8"),
  )

  if (staleOutputs.length > 0) {
    console.error("Brand assets are out of sync:")
    for (const output of staleOutputs) {
      console.error(`- ${output}`)
    }
    console.error("Run `pnpm assets:sync` from the repository root.")
    process.exitCode = 1
  } else if (isCheck) {
    console.log("Brand assets are synchronized.")
  } else {
    console.log("Brand assets synchronized.")
  }
}

async function synchronizeOutput(relativePath: string, expected: Buffer): Promise<void> {
  const absolutePath = resolveRepositoryPath(relativePath)
  const current = await readOptionalFile(absolutePath)

  if (current?.equals(expected)) {
    return
  }

  if (isCheck) {
    staleOutputs.push(relativePath)
    return
  }

  await mkdir(path.dirname(absolutePath), { recursive: true })
  await writeFile(absolutePath, expected)
}

async function readOptionalFile(filePath: string): Promise<Buffer | null> {
  try {
    return await readFile(filePath)
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return null
    }
    throw error
  }
}

function createRuntimeFaviconModule(favicon: Buffer): string {
  const dataUrl = `data:image/x-icon;base64,${favicon.toString("base64")}`
  return [
    "// Generated by scripts/assets/sync-brand-assets.ts from assets/brand/favicon.ico.",
    `export const base64Icon = ${JSON.stringify(dataUrl)}`,
    "",
  ].join("\n")
}

function resolveRepositoryPath(relativePath: string): string {
  return path.join(repositoryRoot, relativePath)
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error
}
