import { mkdir, readFile, writeFile } from "node:fs/promises"
import path from "node:path"
import { fileURLToPath } from "node:url"

import sharp from "sharp"

const repositoryRoot = fileURLToPath(new URL("../../", import.meta.url))

const sourceFiles = {
  favicon: "assets/brand/favicon.webp",
  individuation: "assets/brand/individuation.webp",
} as const

type SourceName = keyof typeof sourceFiles

interface BinaryOutput {
  destination: string
  source: SourceName
}

const binaryOutputs: readonly BinaryOutput[] = [
  {
    destination: "apps/docs/public/nami-favicon.webp",
    source: "favicon",
  },
  {
    destination: "apps/webui/public/nami-favicon.webp",
    source: "favicon",
  },
  {
    destination: "apps/webui/public/individuation.webp",
    source: "individuation",
  },
]

const faviconDestinations = [
  "apps/docs/public/favicon.ico",
  "apps/docs/public/nami-favicon.ico",
  "apps/webui/public/favicon.ico",
  "apps/webui/public/nami-favicon.ico",
] as const
const faviconSizes = [16, 32, 48, 64, 128, 256] as const
const runtimeFaviconDestination = "apps/runtime/src/assets/favicon.ts"
const isCheck = process.argv.slice(2).includes("--check")
const unknownArguments = process.argv.slice(2).filter((argument) => argument !== "--check")
const staleOutputs: string[] = []

main().catch((error: unknown) => {
  const message = error instanceof Error ? error.message : String(error)
  console.error(`Brand asset synchronization failed: ${message}`)
  process.exitCode = 1
})

async function main(): Promise<void> {
  if (unknownArguments.length > 0) {
    throw new Error(`Unknown arguments: ${unknownArguments.join(", ")}`)
  }

  const sourceBuffers = new Map<SourceName, Buffer>()

  for (const [name, relativePath] of Object.entries(sourceFiles) as [SourceName, string][]) {
    sourceBuffers.set(name, await readFile(resolveRepositoryPath(relativePath)))
  }

  for (const output of binaryOutputs) {
    const source = sourceBuffers.get(output.source)
    if (!source) {
      throw new Error(`Brand asset source was not loaded: ${output.source}`)
    }
    await synchronizeOutput(output.destination, source)
  }

  const faviconSource = sourceBuffers.get("favicon")
  if (!faviconSource) {
    throw new Error("Brand favicon source was not loaded")
  }
  const favicon = await createFavicon(faviconSource)

  for (const destination of faviconDestinations) {
    await synchronizeOutput(destination, favicon)
  }

  await synchronizeOutput(
    runtimeFaviconDestination,
    Buffer.from(createRuntimeFaviconModule(favicon), "utf8"),
  )

  if (staleOutputs.length > 0) {
    console.error("Brand assets are out of sync:")
    for (const output of staleOutputs) {
      console.error(`- ${output}`)
    }
    console.error("Run `pnpm assets:sync` from the repository root.")
    process.exitCode = 1
  } else if (isCheck) {
    console.log("Brand assets are synchronized.")
  } else {
    console.log("Brand assets synchronized.")
  }
}

async function synchronizeOutput(relativePath: string, expected: Buffer): Promise<void> {
  const absolutePath = resolveRepositoryPath(relativePath)
  const current = await readOptionalFile(absolutePath)

  if (current?.equals(expected)) {
    return
  }

  if (isCheck) {
    staleOutputs.push(relativePath)
    return
  }

  await mkdir(path.dirname(absolutePath), { recursive: true })
  await writeFile(absolutePath, expected)
}

async function readOptionalFile(filePath: string): Promise<Buffer | null> {
  try {
    return await readFile(filePath)
  } catch (error) {
    if (isNodeError(error) && error.code === "ENOENT") {
      return null
    }
    throw error
  }
}

function createRuntimeFaviconModule(favicon: Buffer): string {
  const dataUrl = `data:image/x-icon;base64,${favicon.toString("base64")}`
  return [
    "// Generated by scripts/assets/sync-brand-assets.ts from assets/brand/favicon.webp.",
    `export const base64Icon = ${JSON.stringify(dataUrl)}`,
    "",
  ].join("\n")
}

async function createFavicon(source: Buffer): Promise<Buffer> {
  const images = await Promise.all(
    faviconSizes.map((size) => sharp(source)
      .resize(size, size, {
        fit: "contain",
        background: { r: 0, g: 0, b: 0, alpha: 0 },
      })
      .png({ compressionLevel: 9, adaptiveFiltering: false })
      .toBuffer()),
  )
  const directorySize = 6 + images.length * 16
  const directory = Buffer.alloc(directorySize)
  directory.writeUInt16LE(0, 0)
  directory.writeUInt16LE(1, 2)
  directory.writeUInt16LE(images.length, 4)

  let imageOffset = directorySize
  for (const [index, image] of images.entries()) {
    const size = faviconSizes[index]
    if (!size) {
      throw new Error(`Missing favicon size for image ${index}`)
    }
    const entryOffset = 6 + index * 16
    directory.writeUInt8(size === 256 ? 0 : size, entryOffset)
    directory.writeUInt8(size === 256 ? 0 : size, entryOffset + 1)
    directory.writeUInt8(0, entryOffset + 2)
    directory.writeUInt8(0, entryOffset + 3)
    directory.writeUInt16LE(1, entryOffset + 4)
    directory.writeUInt16LE(32, entryOffset + 6)
    directory.writeUInt32LE(image.length, entryOffset + 8)
    directory.writeUInt32LE(imageOffset, entryOffset + 12)
    imageOffset += image.length
  }

  return Buffer.concat([directory, ...images])
}

function resolveRepositoryPath(relativePath: string): string {
  return path.join(repositoryRoot, relativePath)
}

function isNodeError(error: unknown): error is NodeJS.ErrnoException {
  return error instanceof Error && "code" in error
}
